[package]
workspace = ".."
name = "11"
version = "0.1.0"
authors = ["Dmitry Kudriavtsev <dkudriavtsev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
