#!/usr/bin/env ruby

# Advent of Code Day 3 Part 1

input = File.read('input.txt').split(',').map { |loc| [ { ?U => :up, ?D => :down, ?L => :left, ?R => :right }[loc[0]], loc[1..-1].to_i ] }

c = [0, 0]

p input.map { |i|
  dist = i[1]
  case i[0]
  when :up
    c[1] += dist
  when :down
    c[1] -= dist
  when :left
    c[0] -= dist
  when :right
    c[0] += dist
  end
  [c[0], c[1]]
}
